name: '_Cypress Tests'

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to deploy'
        required: true
        type: string
      git-ref:
        description: 'Commit/branch which should be deployed'
        required: false
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Run e2e test
        run: yarn test
